### Create measurement
POST localhost:8080/api/v1/measurement/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NTkyNTQsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDc0NTY1NCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oOdYcxRyk0Dh_K9diIv6kDNLYpXMlGjjhxdsx-ZXwvMVwEjbKp3MOrI-uTbyazk8Y00VkOJ-MQPQAkfBhzUcbA
Content-Type:  application/json

{
  "name": "Oqsuv1"
}


### Update measurement
PUT localhost:8080/api/v1/measurement/private/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NTkyNTQsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDc0NTY1NCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oOdYcxRyk0Dh_K9diIv6kDNLYpXMlGjjhxdsx-ZXwvMVwEjbKp3MOrI-uTbyazk8Y00VkOJ-MQPQAkfBhzUcbA
Content-Type:  application/json

{
  "name": "Olmazor"
}

### Delete measurement
DELETE localhost:8080/api/v1/measurement/private/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NTkyNTQsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDc0NTY1NCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oOdYcxRyk0Dh_K9diIv6kDNLYpXMlGjjhxdsx-ZXwvMVwEjbKp3MOrI-uTbyazk8Y00VkOJ-MQPQAkfBhzUcbA

### List of measurement
GET localhost:8080/api/v1/measurement/private/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ2NTkyNTQsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDc0NTY1NCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oOdYcxRyk0Dh_K9diIv6kDNLYpXMlGjjhxdsx-ZXwvMVwEjbKp3MOrI-uTbyazk8Y00VkOJ-MQPQAkfBhzUcbA

