### Create warehouse
POST localhost:8080/api/v1/warehouse/private/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1Nzc1MjEsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDY2MzkyMSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oyDsQb9Z9eU1Oh7qjbmO5xjuonavlZyHdoqWONaKTAdl3zkBhPqT4cvQAi4i1mMauglWkZSciOWT3PL1kFJ43g
Content-Type:  application/json

{
  "name": "Sklad 11"
}


### Update warehouse
PUT localhost:8080/api/v1/warehouse/private/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1Nzc1MjEsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDY2MzkyMSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oyDsQb9Z9eU1Oh7qjbmO5xjuonavlZyHdoqWONaKTAdl3zkBhPqT4cvQAi4i1mMauglWkZSciOWT3PL1kFJ43g
Content-Type:  application/json

{
  "name": "Sklad 5"
}

### Delete warehouse
DELETE localhost:8080/api/v1/warehouse/private/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1Nzc1MjEsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDY2MzkyMSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oyDsQb9Z9eU1Oh7qjbmO5xjuonavlZyHdoqWONaKTAdl3zkBhPqT4cvQAi4i1mMauglWkZSciOWT3PL1kFJ43g

### List of warehouse
GET localhost:8080/api/v1/warehouse/private/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1Nzc1MjEsInBob25lIjoiMTIzNDUiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTY4NDY2MzkyMSwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.oyDsQb9Z9eU1Oh7qjbmO5xjuonavlZyHdoqWONaKTAdl3zkBhPqT4cvQAi4i1mMauglWkZSciOWT3PL1kFJ43g

